brew "chezmoi"
brew "emojify"
brew "gh"
brew "ghq"
brew "git"
brew "mas"
brew "peco"
brew "stow"
brew "the_silver_searcher"
brew "tmux"
brew "trash", link: true
brew "tree"
brew "vim"
cask "alfred"
cask "ankerwork"
cask "applite"
cask "bettertouchtool"
cask "brewlet"
cask "cork"
cask "github"
cask "google-japanese-ime"
cask "hammerspoon"
cask "karabiner-elements"
cask "lastpass"
cask "obsidian"
cask "vivaldi"
cask "warp"
mas "Display Menu", id: 549083868
mas "LensOCR", id: 1549961729
mas "The Unarchiver", id: 425424353
mas "Usage", id: 1561788435
