--[[
-------------------------------------------------------------------------------
--                           カーソル移動                                    --
-------------------------------------------------------------------------------
--]]
-- vim.g.neovide_cursor_animation_length = 0 -- カーソル移動時のアニメーションをオフにする
-- vim.g.neovide_cursor_trail_size = 0       -- カーソル移動時の残像をオフにする
-- vim.g.neovide_cursor_antialiasing = false -- カーソルがぼやけて表示されるのを防ぐ
-- vim.g.neovide_cursor_vfx_mode = ""        -- カーソルのエフェクトを無効化する
--
--
-- --[[
-- -------------------------------------------------------------------------------
-- --                           ウィンドウ表示                                  --
-- -------------------------------------------------------------------------------
-- --]]
-- vim.g.neovide_remember_window_size = false -- ウィンドウサイズを記憶しない(BTT側で調整するため)
-- vim.g.neovide_padding_top = 0              -- ウィンドウの余白をなくす
-- vim.g.neovide_padding_bottom = 0           -- ウィンドウの余白をなくす
-- vim.g.neovide_padding_right = 0            -- ウィンドウの余白をなくす
-- vim.g.neovide_padding_left = 0             -- ウィンドウの余白をなくす
--
-- vim.opt.guifont = "Hiragino Sans:h12"      -- macOSの場合の例
-- vim.g.neovide_input_ime = true
--[[
-------------------------------------------------------------------------------
--                           外観                                            --
-------------------------------------------------------------------------------
--]]
-- local title_name = "📝ワーキングメモ"
-- vim.opt.title = true -- ウィンドウタイトルを有効化
-- vim.opt.background = "light" -- 背景色をライトモードに設定
-- vim.opt.titlestring = title_name -- 日本語を直接セットするとLinterがズレるので変数経由でセットしている
-- vim.opt.guifont = "Menlo:h18"    -- フォントとサイズを指定
